### ISSUE TITLE
Falla el Autograding ...

### ISSUE THREAD

**Issue by ricardo-quintero** [itc-mcc/strategy-garay54#3]
Algo tiene tu proyecto que no pasa el autograding ...

**Comment by garay54** [comment]
voy a revisarlo profesor

**Comment by garay54** [comment]
puede volver a revisar maestro?, lo corro en la parte de actions el que tiene el titulo de final y si me hace el autograding

**Comment by ricardo-quintero** [comment]
Ok, lo reviso y te comento ...

**Comment by ricardo-quintero** [comment]
De acuerdo, ya quedó resuelto ...

**Comment by garay54** [comment]
excelente, me faltaba actualizarlo para que estuviera en el principal lo que se debía entregar
